### ISSUE TITLE
"NoneType object is not iterable" stackdump when 0 hits found

### ISSUE THREAD

**Issue by petermr** [petermr/pygetpapers#14]
```
(base) pm286macbook:physchem pm286$ pygetpapers -q kbsdcsdcsdck 
INFO: Total Hits are 0
WARNING: Could not find more papers
Traceback (most recent call last):
  File "/opt/anaconda3/bin/pygetpapers", line 8, in <module>
    sys.exit(main())
  File "/opt/anaconda3/lib/python3.8/site-packages/pygetpapers/pygetpapers.py", line 655, in main
    callpygetpapers.handlecli()
  File "/opt/anaconda3/lib/python3.8/site-packages/pygetpapers/pygetpapers.py", line 634, in handlecli
    self.apipaperdownload(args.query, args.limit,
  File "/opt/anaconda3/lib/python3.8/site-packages/pygetpapers/pygetpapers.py", line 452, in apipaperdownload
    self.makecsv(query_result, makecsv=makecsv, makehtml=makehtml)
  File "/opt/anaconda3/lib/python3.8/site-packages/pygetpapers/pygetpapers.py", line 59, in makecsv
    for paper_number, papers in enumerate(searchvariable):
TypeError: 'NoneType' object is not iterable
(base) pm286macbook:physchem pm286$ 
```

**Comment by ayush4921** [comment]
This has already been dealt with in a previous patch. Please update the repo and try again. On my pygetpapers, this is the output:
![image](https://user-images.githubusercontent.com/62711517/117225560-3334b200-ae45-11eb-842f-c05a8b8aed3d.png)
